name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Jaguar Toolchain
        run: make

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Package VS Code Extension
        run: |
          cd jaguar-lang-extension
          npm install
          npx vsce package
          mv *.vsix ..

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            jag
            *.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
